/********************* SHARE - CARGA DE DIMENSIONES **************************/

/****** CARGA DE CATALOGO PAISES **********/

MERGE INTO SHARE_DIM_PAISES D
USING (SELECT DISTINCT PAIS FROM SHARE_TMP_CLAVECORTAPAIS_INFO_CARGA WHERE NOT PAIS IS NULL)TMP
ON (D.GV_PAIS=TMP.PAIS)
WHEN NOT MATCHED THEN
INSERT(PK_PAIS, GV_PAIS)
VALUES(SEQ_PK_PAIS_SHARE.NEXTVAL,TMP.PAIS);
COMMIT;

/****** CARGA DE CATALOGO CANALES **********/

MERGE INTO SHARE_DIM_CANALES D
USING (SELECT DISTINCT CANAL FROM SHARE_TMP_CLAVECORTAPAIS_INFO_CARGA WHERE NOT CANAL IS NULL)TMP
ON (D.GV_CANAL=TMP.CANAL)
WHEN NOT MATCHED THEN
INSERT(PK_CANAL, GV_CANAL)
VALUES(SEQ_PK_CANAL_SHARE.NEXTVAL,TMP.CANAL);
COMMIT;

/****** CARGA DE CATALOGO GRUPO DE CATEGORIAS **********/

MERGE INTO SHARE_DIM_GRUPO_CATEGORIAS D
USING (SELECT DISTINCT GRUPO_CATEGORIA FROM SHARE_TMP_CLAVECORTAPAIS_INFO_CARGA WHERE NOT GRUPO_CATEGORIA IS NULL)TMP
ON (D.GV_GRUPO_CATEGORIA=TMP.GRUPO_CATEGORIA)
WHEN NOT MATCHED THEN
INSERT(PK_GRUPO_CATEGORIA, GV_GRUPO_CATEGORIA)
VALUES(SEQ_PK_G_CAT_SHARE.NEXTVAL,TMP.GRUPO_CATEGORIA);
COMMIT;

/****** CARGA DE CATALOGO CATEGORIAS **********/

MERGE INTO SHARE_DIM_CATEGORIAS D
USING (SELECT DISTINCT CATEGORIA FROM SHARE_TMP_CLAVECORTAPAIS_INFO_CARGA WHERE NOT CATEGORIA IS NULL)TMP
ON (D.GV_CATEGORIA=TMP.CATEGORIA)
WHEN NOT MATCHED THEN
INSERT(PK_CATEGORIA, GV_CATEGORIA)
VALUES(SEQ_PK_CAT_SHARE.NEXTVAL,TMP.CATEGORIA);
COMMIT;

/****** CARGA DE CATALOGO FABRICANTES **********/

MERGE INTO SHARE_DIM_FABRICANTES D
USING (SELECT DISTINCT FABRICANTE FROM SHARE_TMP_CLAVECORTAPAIS_INFO_CARGA WHERE NOT FABRICANTE IS NULL)TMP
ON (D.GV_FABRICANTE=TMP.FABRICANTE)
WHEN NOT MATCHED THEN
INSERT(PK_FABRICANTE, GV_FABRICANTE)
VALUES(SEQ_PK_FAB_SHARE.NEXTVAL,TMP.FABRICANTE);
COMMIT;

EXIT;
