/********************* SHARE - CARGA DE TABLA TEMPORAL **************************/

/****** INSERTA REGISTROS DE ARCHIVO A TABLA TEMPORAL **********/
TRUNCATE TABLE SHARE_TMP_CLAVECORTAPAIS_INFO;
COMMIT;

INSERT INTO SHARE_TMP_CLAVECORTAPAIS_INFO
SELECT
UPPER(FECHA) AS FECHA,
TO_NUMBER('20'||SUBSTR(FECHA,LENGTH(FECHA)-1,2)) AS ANIO,
UPPER(SUBSTR(FECHA,1,3)) AS MES,
NULL AS TIEMPO,
PK_PAIS,
PAIS,
PK_GRUPO_CATEGORIA,
GRUPO_CATEGORIA,
PK_CATEGORIA,
CATEGORIA,
PK_CANAL PK_CANAL,
CANAL AS CANAL,
PK_FABRICANTE,
FABRICANTE,
NULL AS VOLUMEN_AA,
NULL AS VOLUMEN_AA_KOF,
NULL AS VOLUMEN_AA_TOTAL,
NULL AS VOLUMEN_MA,
NULL AS VOLUMEN_MA_KOF,
NULL AS VOLUMEN_MA_TOTAL,
SUM(VOLUMEN_MES),
NULL AS VOLUMEN_MES_KOF,
NULL AS VOLUMEN_MES_TOTAL,
NULL AS VENTA_AA,
NULL AS VENTA_AA_KOF,
NULL AS VENTA_AA_TOTAL,
NULL AS VENTA_MA,
NULL AS VENTA_MA_KOF,
NULL AS VENTA_MA_TOTAL,
SUM(VENTA_MES),
NULL AS VENTA_MES_KOF,
NULL AS VENTA_MES_TOTAL,
NULL AS VOLUMEN_YTD_AA,
NULL AS VOLUMEN_YTD_AA_KOF,
NULL AS VOLUMEN_YTD_AA_TOTAL,
NULL AS VOLUMEN_YTD,
NULL AS VOLUMEN_YTD_KOF,
NULL AS VOLUMEN_YTD_TOTAL,
NULL AS VENTA_YTD_AA,
NULL AS VENTA_YTD_AA_KOF,
NULL AS VENTA_YTD_AA_TOTAL,
NULL AS VENTA_YTD,
NULL AS VENTA_YTD_KOF,
NULL AS VENTA_YTD_TOTAL
FROM SHARE_TMP_CLAVECORTAPAIS_INFO_CARGA TMP
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS = DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA = DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIAS DC
ON TMP.CATEGORIA = DC.GV_CATEGORIA
LEFT JOIN SHARE_DIM_CANALES DCAN
ON TMP.CANAL = DCAN.GV_CANAL
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE = DF.GV_FABRICANTE
GROUP BY FECHA,
PK_PAIS,PAIS,
PK_GRUPO_CATEGORIA,GRUPO_CATEGORIA,
PK_CATEGORIA,CATEGORIA,
PK_CANAL,CANAL,
PK_FABRICANTE,FABRICANTE;
COMMIT;

/****** ACTUALIZACIÓN DE CAMPOS TIEMPO **********/

UPDATE SHARE_TMP_CLAVECORTAPAIS_INFO TMP SET TMP.TIEMPO = (SELECT ID_TIEMPO FROM SHARE_DIM_TIEMPO DIM WHERE TMP.ANIO=DIM.GV_ANIO AND TMP.MES= UPPER(DIM.GV_MESCORTO));
COMMIT;
