/********************* SHARE - CARGA DE TABLA TEMPORAL *********************/

/****** INSERTA REGISTROS SUMARIZADOS DE ARCHIVO A TABLA TEMPORAL **********/
TRUNCATE TABLE SHARE_TMP_COL_INFO;
COMMIT;

INSERT INTO SHARE_TMP_COL_INFO
SELECT
ANIO,
MES,
TIEMPO,
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE,
RETORNABILIDAD,
SUM(VOLUMEN_MES) AS VOLUMES_MES,
NULL AS VOLUMEN_MES_KOF,
NULL AS VOLUMEN_MA,
NULL AS VOLUMEN_MA_KOF,
NULL AS VOLUMEN_AA,
NULL AS VOLUMEN_AA_KOF,
NULL AS VOLUMEN_YTD,
NULL AS VOLUMEN_YTD_KOF,
NULL AS VOLUMEN_YTD_AA,
NULL AS VOLUMEN_YTD_AA_KOF,
SUM(VENTA_MES) AS VENTA_MES,
NULL AS VENTA_MES_KOF,
NULL AS VENTA_MA,
NULL AS VENTA_MA_KOF,
NULL AS VENTA_AA,
NULL AS VENTA_AA_KOF,
NULL AS VENTA_YTD,
NULL AS VENTA_YTD_KOF,
NULL AS VENTA_YTD_AA,
NULL AS VENTA_YTD_AA_KOF
FROM SHARE_TMP_COL_INFO_CARGA
GROUP BY 
ANIO,
MES,
TIEMPO,
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE,
RETORNABILIDAD;
COMMIT;

