/*************** SHARE - CALCULA LOS INDICADORES AA, MA, YTD PARA VOLUMEN Y VENTAS ***************/

/********** INSERTA REGISTROS DE ARCHIVO A TABLA AA **********/
TRUNCATE TABLE SHARE_TMP_COL_INFO_AA;
COMMIT;
 
INSERT INTO SHARE_TMP_COL_INFO_AA
SELECT  
ANIO,
MES,
TIEMPO,
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE, 
RETORNABILIDAD,
VOLUMEN_MES,
VOLUMEN_MES_KOF,
VOLUMEN_MA,
VOLUMEN_MA_KOF,
VOLUMEN_AA,
VOLUMEN_AA_KOF,
VOLUMEN_YTD,
VOLUMEN_YTD_KOF,
VOLUMEN_YTD_AA,
VOLUMEN_YTD_AA_KOF,
VENTA_MES,
VENTA_MES_KOF,
VENTA_MA,
VENTA_MA_KOF,
VENTA_AA,
VENTA_AA_KOF,
VENTA_YTD,
VENTA_YTD_KOF,
VENTA_YTD_AA,
VENTA_YTD_AA_KOF,
NULL AS ANIO_AA,
NULL AS MES_AA
FROM SHARE_TMP_COL_INFO;
 
/****************************************** CALCULOS DE VALORES MENSUALES  ******************************************/

/****** BUSCA VALOR DEL A�O ANTERIOR ******/  
UPDATE SHARE_TMP_COL_INFO_AA SET ANIO_AA = 1 
WHERE ANIO IN (SELECT DISTINCT ANIO-1 FROM SHARE_TMP_COL_INFO) AND MES IN(SELECT DISTINCT MES FROM SHARE_TMP_COL_INFO);
COMMIT;

/****** BUSCA VALOR DEL MES ANTERIOR (SIN ENERO)******/
UPDATE SHARE_TMP_COL_INFO_AA SET MES_AA = 1 
WHERE TIEMPO IN (SELECT DISTINCT TIEMPO-1 FROM SHARE_TMP_COL_INFO) AND MES!=1;
  COMMIT;

/****** BUSCA VALOR DEL MES ANTERIOR (SOLO ENERO)******/
UPDATE SHARE_TMP_COL_INFO_AA SET MES_AA = 1 
WHERE ANIO IN (SELECT DISTINCT ANIO-1 FROM SHARE_TMP_COL_INFO) AND MES IN(SELECT DISTINCT MES FROM SHARE_TMP_COL_INFO WHERE MES = 12) 
AND MES=1;
COMMIT;

/****** INSERTA VALORES DEL A�O ANTERIOR ******/ 

INSERT INTO SHARE_TMP_COL_INFO_AA
SELECT  
ANIO,
MES,
TIEMPO + 100,
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE,
RETORNABILIDAD,
NULL AS VOLUMEN_MES,
NULL AS VOLUMEN_MES_KOF,
NULL AS VOLUMEN_MA,
NULL AS VOLUMEN_MA_KOF,
VOLUMEN_MES AS VOLUMEN_AA,
NULL AS VOLUMEN_AA_KOF,
NULL AS VOLUMEN_YTD,
NULL AS VOLUMEN_YTD_KOF,
NULL AS VOLUMEN_YTD_AA,
NULL AS VOLUMEN_YTD_AA_KOF,
NULL AS VENTA_MES,
NULL AS VENTA_MES_KOF,
NULL AS VENTA_MA,
NULL AS VENTA_MA_KOF,
VENTA_MES AS VENTA_AA,
NULL AS VENTA_AA_KOF,
NULL AS VENTA_YTD,
NULL AS VENTA_YTD_KOF,
NULL AS VENTA_YTD_AA,
NULL AS VENTA_YTD_AA_KOF,
NULL AS ANIO_AA,
NULL AS MES_AA
FROM SHARE_TMP_COL_INFO_AA 
WHERE ANIO_AA = 1 ;
COMMIT;

/****** INSERTA VALORES DEL MES ANTERIOR (SIN ENERO)******/ 
INSERT INTO SHARE_TMP_COL_INFO_AA
SELECT  
ANIO,
MES,
TIEMPO + 1,
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE,
RETORNABILIDAD,
NULL AS VOLUMEN_MES,
NULL AS VOLUMEN_MES_KOF,
VOLUMEN_MES AS VOLUMEN_MA,
NULL AS VOLUMEN_MA_KOF,
NULL AS VOLUMEN_AA,
NULL AS VOLUMEN_AA_KOF,
NULL AS VOLUMEN_YTD,
NULL AS VOLUMEN_YTD_KOF,
NULL AS VOLUMEN_YTD_AA,
NULL AS VOLUMEN_YTD_AA_KOF,
NULL AS VENTA_MES,
NULL AS VENTA_MES_KOF,
VENTA_MES AS VENTA_MA,
NULL AS VENTA_MA_KOF,
NULL AS VENTA_AA,
NULL AS VENTA_AA_KOF,
NULL AS VENTA_YTD,
NULL AS VENTA_YTD_KOF,
NULL AS VENTA_YTD_AA,
NULL AS VENTA_YTD_AA_KOF,
NULL AS ANIO_AA,
NULL AS MES_AA
FROM SHARE_TMP_COL_INFO_AA 
WHERE MES_AA = 1 ;
COMMIT;

/****** INSERTA VALORES DEL MES ANTERIOR (SOLO ENERO)******/ 
INSERT INTO SHARE_TMP_COL_INFO_AA
SELECT  
ANIO,
MES,
TIEMPO + 100,
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE,
RETORNABILIDAD,
NULL AS VOLUMEN_MES,
NULL AS VOLUMEN_MES_KOF,
VOLUMEN_MES AS VOLUMEN_MA,
NULL AS VOLUMEN_MA_KOF,
NULL AS VOLUMEN_AA,
NULL AS VOLUMEN_AA_KOF,
NULL AS VOLUMEN_YTD,
NULL AS VOLUMEN_YTD_KOF,
NULL AS VOLUMEN_YTD_AA,
NULL AS VOLUMEN_YTD_AA_KOF,
NULL AS VENTA_MES,
NULL AS VENTA_MES_KOF,
VENTA_MES AS VENTA_MA,
NULL AS VENTA_MA_KOF,
NULL AS VENTA_AA,
NULL AS VENTA_AA_KOF,
NULL AS VENTA_YTD,
NULL AS VENTA_YTD_KOF,
NULL AS VENTA_YTD_AA,
NULL AS VENTA_YTD_AA_KOF,
NULL AS ANIO_AA,
NULL AS MES_AA
FROM SHARE_TMP_COL_INFO_AA 
WHERE MES_AA = 1 AND MES = 12 ;
COMMIT;

/****************************************** CALCULOS DE VALORES ACUMULADOS  ******************************************/

/****** CALCULA VALOR YTD VOLUMEN Y VENTA******/    

CREATE OR REPLACE PROCEDURE CALCULASHAREYTD IS 

PROCEDURE CALCULASHAREYTD IS

CURSOR C1 IS 
SELECT DISTINCT
ANIO,
MES,
TIEMPO
FROM SHARE_TMP_COL_INFO;

Y INTEGER;
M INTEGER;
P INTEGER;

BEGIN
  FOR ITEM IN C1
LOOP

  Y:= TO_NUMBER(ITEM.ANIO);
  M:= TO_NUMBER(ITEM.MES);
  P:= TO_NUMBER(ITEM.TIEMPO);   
  
INSERT INTO SHARE_TMP_COL_INFO_AA
SELECT  
Y,
M,
P,
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE, 
RETORNABILIDAD,
NULL AS VOLUMEN_MES,
NULL AS VOLUMEN_MES_KOF,
NULL AS VOLUMEN_MA,
NULL AS VOLUMEN_MA_KOF,
NULL AS VOLUMEN_AA,
NULL AS VOLUMEN_AA_KOF,
SUM(VOLUMEN_MES) AS VOLUMEN_YTD,
NULL AS VOLUMEN_YTD_KOF,
NULL AS VOLUMEN_YTD_AA,
NULL AS VOLUMEN_YTD_AA_KOF,
NULL AS VENTA_MES,
NULL AS VENTA_MES_KOF,
NULL AS VENTA_MA,
NULL AS VENTA_MA_KOF,
NULL AS VENTA_AA,
NULL AS VENTA_AA_KOF,
SUM(VENTA_MES) AS VENTA_YTD,
NULL AS VENTA_YTD_KOF,
NULL AS VENTA_YTD_AA,
NULL AS VENTA_YTD_AA_KOF,
NULL AS ANIO_AA,
NULL AS MES_AA
FROM SHARE_TMP_COL_INFO
          WHERE SHARE_TMP_COL_INFO.ANIO = Y 
          AND SHARE_TMP_COL_INFO.TIEMPO <= P
GROUP BY
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE,
RETORNABILIDAD;
COMMIT;  
       
END LOOP;

END;

BEGIN
CALCULASHAREYTD;
END;
                
EXECUTE CALCULASHAREYTD;
COMMIT;


/****** CALCULA VALOR YTD A�O ANTERIOR VOLUMEN Y VENTA******/ 

CREATE OR REPLACE PROCEDURE CALCULASHAREYTDAA IS 

PROCEDURE CALCULASHAREYTDAA IS

CURSOR C1 IS 
SELECT DISTINCT
ANIO,
MES,
TIEMPO
FROM SHARE_TMP_COL_INFO;

Y INTEGER;
M INTEGER;
P INTEGER;

BEGIN
  FOR ITEM IN C1
LOOP

  Y:= TO_NUMBER(ITEM.ANIO);
  M:= TO_NUMBER(ITEM.MES);
  P:= TO_NUMBER(ITEM.TIEMPO);  
  
INSERT INTO SHARE_TMP_COL_INFO_AA
SELECT  
Y,
M,
P,
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE, 
RETORNABILIDAD,
NULL AS VOLUMEN_MES,
NULL AS VOLUMEN_MES_KOF,
NULL AS VOLUMEN_MA,
NULL AS VOLUMEN_MA_KOF,
NULL AS VOLUMEN_AA,
NULL AS VOLUMEN_AA_KOF,
NULL AS VOLUMEN_YTD,
NULL AS VOLUMEN_YTD_KOF,
SUM(VOLUMEN_MES) VOLUMEN_YTD_AA,
NULL AS VOLUMEN_YTD_AA_KOF,
NULL AS VENTA_MES,
NULL AS VENTA_MES_KOF,
NULL AS VENTA_MA,
NULL AS VENTA_MA_KOF,
NULL AS VENTA_AA,
NULL AS VENTA_AA_KOF,
NULL AS VENTA_YTD,
NULL AS VENTA_YTD_KOF,
SUM(VENTA_MES) VENTA_YTD_AA,
NULL AS VENTA_YTD_AA_KOF,
NULL AS ANIO_AA,
NULL AS MES_AA
FROM SHARE_TMP_COL_INFO
          WHERE SHARE_TMP_COL_INFO.ANIO = Y - 1
          AND SHARE_TMP_COL_INFO.TIEMPO <= P - 100
GROUP BY
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE,
RETORNABILIDAD;
COMMIT;  
       
END LOOP;

END;

BEGIN
CALCULASHAREYTDAA;
END;
         
EXECUTE CALCULASHAREYTDAA;
COMMIT;

EXIT;


