/********************* SHARE - INSERTA REGISTROS EN TABLAS ST  **************************/

/****** ELIMINA REGISTROS EXISTENTES DE TABLA ST GRUPO DE CATEGORIA**********/

DELETE FROM SHARE_ST_INFO
WHERE PAIS = 'COLOMBIA';
COMMIT;


/****** INSERTA REGISTROS SUMARIZADOS A TABLA ST GENERAL ******/ 

INSERT INTO SHARE_ST_INFO
SELECT
TIEMPO,
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE,
RETORNABILIDAD,
SUM(VOLUMEN_MES) as VOLUMEN_MES,
NULL AS VOLUMEN_MES_KOF,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
NULL AS VOLUMEN_MA_KOF,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
NULL AS VOLUMEN_AA_KOF,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
NULL AS VOLUMEN_YTD_KOF,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
NULL AS VOLUMEN_YTD_AA_KOF,
SUM(VENTA_MES) AS VENTA_MES,
NULL AS VENTA_MES_KOF,
SUM(VENTA_MA) AS VENTA_MA,
NULL AS VENTA_MA_KOF,
SUM(VENTA_AA) AS VENTA_AA,
NULL AS VENTA_AA_KOF,
SUM(VENTA_YTD) AS VENTA_YTD,
NULL AS VENTA_YTD_KOF,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA,
NULL AS VENTA_YTD_AA_KOF
FROM SHARE_TMP_COL_INFO_AA
GROUP BY 
TIEMPO,
PAIS,
UNIDAD_NEGOCIO,
CANAL,
SUBCANAL,
UNIDAD_OPERATIVA,
REGION,
ZONA,
GRUPO_CATEGORIA,
CATEGORIA,
FABRICANTE,
MARCA,
SABOR,
TAMANO,
EMPAQUE,
RETORNABILIDAD;
COMMIT;

EXIT; 
