/********************* SHARE - INSERTA REGISTROS EN TABLAS ST  **************************/

/****** ELIMINA REGISTROS EXISTENTES DE TABLA ST GRUPO DE CATEGORIA**********/

DELETE FROM SHARE_ST_INFO_G_CAT ST
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** INSERTA REGISTROS A TABLA ST **********/

INSERT INTO SHARE_ST_INFO_G_CAT
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, FABRICANTE,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_AA_KOF) AS VOLUMEN_AA_KOF,
SUM(VOLUMEN_AA_TOTAL) AS VOLUMEN_AA_TOTAL,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_MA_KOF) AS VOLUMEN_MA_KOF,
SUM(VOLUMEN_MA_TOTAL) AS VOLUMEN_MA_TOTAL,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MES_KOF) AS VOLUMEN_MES_KOF,
SUM(VOLUMEN_MES_TOTAL) AS VOLUMEN_MES_TOTAL,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_AA_KOF) AS VENTA_AA_KOF,
SUM(VENTA_AA_TOTAL) AS VENTA_AA_TOTAL,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_MA_KOF) AS VENTA_MA_KOF,
SUM(VENTA_MA_TOTAL) AS VENTA_MA_TOTAL,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MES_KOF) AS VENTA_MES_KOF,
SUM(VENTA_MES_TOTAL) AS VENTA_MES_TOTAL,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS VOLUMEN_YTD_AA_KOF,
SUM(VOLUMEN_YTD_AA_TOTAL) AS VOLUMEN_YTD_AA_TOTAL,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_KOF) AS VOLUMEN_YTD_KOF,
SUM(VOLUMEN_YTD_TOTAL) AS VOLUMEN_YTD_TOTAL,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS VENTA_YTD_AA_KOF,
SUM(VENTA_YTD_AA_TOTAL) AS VENTA_YTD_AA_TOTAL,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_KOF) AS VENTA_YTD_KOF,
SUM(VENTA_YTD_TOTAL) AS VENTA_YTD_TOTAL
FROM SHARE_TMP_CLAVECORTAPAIS_INFO
WHERE CANAL LIKE '%TOTAL%'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, FABRICANTE;
COMMIT;

/******* SHARE - CALCULA LOS INDICADORES YTD,MA,AA TOTALES G_CATEGORIA *********************/

CREATE TABLE SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL AS
SELECT * FROM ( SELECT DISTINCT * FROM SHARE_TMP_CLAVECORTAPAIS_INFO
WHERE FABRICANTE LIKE '%TOTAL%' AND CANAL LIKE '%TOTAL%');

UPDATE SHARE_ST_INFO_G_CAT INFO SET INFO.VOLUMEN_AA_TOTAL=(
SELECT SUM(VOLUMEN_AA)
FROM SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT INFO SET INFO.VOLUMEN_MA_TOTAL=(
SELECT SUM(VOLUMEN_MA)
FROM SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT INFO SET INFO.VOLUMEN_MES_TOTAL=(
SELECT SUM(VOLUMEN_MES)
FROM SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT INFO SET INFO.VENTA_AA_TOTAL=(
SELECT SUM(VENTA_AA)
FROM SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT INFO SET INFO.VENTA_MA_TOTAL=(
SELECT SUM(VENTA_MA)
FROM SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT INFO SET INFO.VENTA_MES_TOTAL=(
SELECT SUM(VENTA_MES)
FROM SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT INFO SET INFO.VOLUMEN_YTD_TOTAL=(
SELECT SUM(VOLUMEN_YTD)
FROM SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT INFO SET INFO.VOLUMEN_YTD_AA_TOTAL=(
SELECT SUM(VOLUMEN_YTD_AA)
FROM SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT INFO SET INFO.VENTA_YTD_TOTAL=(
SELECT SUM(VENTA_YTD)
FROM SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT INFO SET INFO.VENTA_YTD_AA_TOTAL=(
SELECT SUM(VENTA_YTD_AA)
FROM SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;


/****** ELIMINAR TABLA TEMPORAL CALCULOS TOTALES *******/
DROP TABLE SHARE_TMP_CLAVECORTAPAIS_G_CAT_TOTAL;


/****** ELIMINA REGISTROS EXISTENTES DE TABLA ST CATEGORIA**********/

DELETE FROM SHARE_ST_INFO_CAT ST
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** INSERTA REGISTROS A TABLA ST **********/

INSERT INTO SHARE_ST_INFO_CAT
SELECT
FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA,FABRICANTE,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_AA_KOF) AS VOLUMEN_AA_KOF,
SUM(VOLUMEN_AA_TOTAL) AS VOLUMEN_AA_TOTAL,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_MA_KOF) AS VOLUMEN_MA_KOF,
SUM(VOLUMEN_MA_TOTAL) AS VOLUMEN_MA_TOTAL,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MES_KOF) AS VOLUMEN_MES_KOF,
SUM(VOLUMEN_MES_TOTAL) AS VOLUMEN_MES_TOTAL,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_AA_KOF) AS VENTA_AA_KOF,
SUM(VENTA_AA_TOTAL) AS VENTA_AA_TOTAL,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_MA_KOF) AS VENTA_MA_KOF,
SUM(VENTA_MA_TOTAL) AS VENTA_MA_TOTAL,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MES_KOF) AS VENTA_MES_KOF,
SUM(VENTA_MES_TOTAL) AS VENTA_MES_TOTAL,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS VOLUMEN_YTD_AA_KOF,
SUM(VOLUMEN_YTD_AA_TOTAL) AS VOLUMEN_YTD_AA_TOTAL,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_KOF) AS VOLUMEN_YTD_KOF,
SUM(VOLUMEN_YTD_TOTAL) AS VOLUMEN_YTD_TOTAL,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS VENTA_YTD_AA_KOF,
SUM(VENTA_YTD_AA_TOTAL) AS VENTA_YTD_AA_TOTAL,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_KOF) AS VENTA_YTD_KOF,
SUM(VENTA_YTD_TOTAL) AS VENTA_YTD_TOTAL
FROM SHARE_TMP_CLAVECORTAPAIS_INFO
WHERE CANAL LIKE '%TOTAL%'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, FABRICANTE;
COMMIT;

/****** ELIMINA REGISTROS EXISTENTES DE TABLA ST CANAL**********/

DELETE FROM SHARE_ST_INFO_CANAL ST
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** INSERTA REGISTROS A TABLA ST **********/

INSERT INTO SHARE_ST_INFO_CANAL
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL, FABRICANTE,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_AA_KOF) AS VOLUMEN_AA_KOF,
SUM(VOLUMEN_AA_TOTAL) AS VOLUMEN_AA_TOTAL,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_MA_KOF) AS VOLUMEN_MA_KOF,
SUM(VOLUMEN_MA_TOTAL) AS VOLUMEN_MA_TOTAL,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MES_KOF) AS VOLUMEN_MES_KOF,
SUM(VOLUMEN_MES_TOTAL) AS VOLUMEN_MES_TOTAL,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_AA_KOF) AS VENTA_AA_KOF,
SUM(VENTA_AA_TOTAL) AS VENTA_AA_TOTAL,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_MA_KOF) AS VENTA_MA_KOF,
SUM(VENTA_MA_TOTAL) AS VENTA_MA_TOTAL,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MES_KOF) AS VENTA_MES_KOF,
SUM(VENTA_MES_TOTAL) AS VENTA_MES_TOTAL,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS VOLUMEN_YTD_AA_KOF,
SUM(VOLUMEN_YTD_AA_TOTAL) AS VOLUMEN_YTD_AA_TOTAL,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_KOF) AS VOLUMEN_YTD_KOF,
SUM(VOLUMEN_YTD_TOTAL) AS VOLUMEN_YTD_TOTAL,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS VENTA_YTD_AA_KOF,
SUM(VENTA_YTD_AA_TOTAL) AS VENTA_YTD_AA_TOTAL,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_KOF) AS VENTA_YTD_KOF,
SUM(VENTA_YTD_TOTAL) AS VENTA_YTD_TOTAL
FROM SHARE_TMP_CLAVECORTAPAIS_INFO
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL, FABRICANTE;
COMMIT;


/****** ELIMINA REGISTROS EXISTENTES DE TABLA ST FABRICANTE**********/

DELETE FROM SHARE_ST_INFO_FAB ST
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** INSERTA REGISTROS A TABLA ST **********/

INSERT INTO SHARE_ST_INFO_FAB
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL, FABRICANTE,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_AA_KOF) AS VOLUMEN_AA_KOF,
SUM(VOLUMEN_AA_TOTAL) AS VOLUMEN_AA_TOTAL,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_MA_KOF) AS VOLUMEN_MA_KOF,
SUM(VOLUMEN_MA_TOTAL) AS VOLUMEN_MA_TOTAL,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MES_KOF) AS VOLUMEN_MES_KOF,
SUM(VOLUMEN_MES_TOTAL) AS VOLUMEN_MES_TOTAL,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_AA_KOF) AS VENTA_AA_KOF,
SUM(VENTA_AA_TOTAL) AS VENTA_AA_TOTAL,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_MA_KOF) AS VENTA_MA_KOF,
SUM(VENTA_MA_TOTAL) AS VENTA_MA_TOTAL,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MES_KOF) AS VENTA_MES_KOF,
SUM(VENTA_MES_TOTAL) AS VENTA_MES_TOTAL,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS VOLUMEN_YTD_AA_KOF,
SUM(VOLUMEN_YTD_AA_TOTAL) AS VOLUMEN_YTD_AA_TOTAL,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_KOF) AS VOLUMEN_YTD_KOF,
SUM(VOLUMEN_YTD_TOTAL) AS VOLUMEN_YTD_TOTAL,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS VENTA_YTD_AA_KOF,
SUM(VENTA_YTD_AA_TOTAL) AS VENTA_YTD_AA_TOTAL,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_KOF) AS VENTA_YTD_KOF,
SUM(VENTA_YTD_TOTAL) AS VENTA_YTD_TOTAL
FROM (SELECT *
FROM SHARE_TMP_CLAVECORTAPAIS_INFO
WHERE CANAL NOT LIKE '%TOTAL%')
WHERE FABRICANTE NOT LIKE '%TOTAL%'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL, FABRICANTE;
COMMIT;

/****** ELIMINA REGISTROS EXISTENTES DE TABLA ST NARTD**********/

DELETE FROM SHARE_ST_INFO_NARTD ST
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** INSERTA REGISTROS A TABLA ST **********/

INSERT INTO SHARE_ST_INFO_NARTD
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, FABRICANTE,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_AA_KOF) AS VOLUMEN_AA_KOF,
SUM(VOLUMEN_AA_TOTAL) AS VOLUMEN_AA_TOTAL,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_MA_KOF) AS VOLUMEN_MA_KOF,
SUM(VOLUMEN_MA_TOTAL) AS VOLUMEN_MA_TOTAL,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MES_KOF) AS VOLUMEN_MES_KOF,
SUM(VOLUMEN_MES_TOTAL) AS VOLUMEN_MES_TOTAL,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_AA_KOF) AS VENTA_AA_KOF,
SUM(VENTA_AA_TOTAL) AS VENTA_AA_TOTAL,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_MA_KOF) AS VENTA_MA_KOF,
SUM(VENTA_MA_TOTAL) AS VENTA_MA_TOTAL,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MES_KOF) AS VENTA_MES_KOF,
SUM(VENTA_MES_TOTAL) AS VENTA_MES_TOTAL,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS VOLUMEN_YTD_AA_KOF,
SUM(VOLUMEN_YTD_AA_TOTAL) AS VOLUMEN_YTD_AA_TOTAL,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_KOF) AS VOLUMEN_YTD_KOF,
SUM(VOLUMEN_YTD_TOTAL) AS VOLUMEN_YTD_TOTAL,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS VENTA_YTD_AA_KOF,
SUM(VENTA_YTD_AA_TOTAL) AS VENTA_YTD_AA_TOTAL,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_KOF) AS VENTA_YTD_KOF,
SUM(VENTA_YTD_TOTAL) AS VENTA_YTD_TOTAL
FROM SHARE_TMP_CLAVECORTAPAIS_INFO
WHERE CANAL LIKE '%TOTAL%'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, FABRICANTE;
COMMIT;


/********************* SHARE - CALCULA LOS INDICADORES YTD,MA,AA TOTALES NARTD **************************/

CREATE TABLE SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL AS
SELECT * FROM ( SELECT DISTINCT * FROM SHARE_TMP_CLAVECORTAPAIS_INFO
WHERE FABRICANTE LIKE '%TOTAL%' AND CANAL LIKE '%TOTAL%');

UPDATE SHARE_ST_INFO_NARTD INFO SET INFO.VOLUMEN_AA_TOTAL=(
SELECT SUM(VOLUMEN_AA)
FROM SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_NARTD INFO SET INFO.VOLUMEN_MA_TOTAL=(
SELECT SUM(VOLUMEN_MA)
FROM SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_NARTD INFO SET INFO.VOLUMEN_MES_TOTAL=(
SELECT SUM(VOLUMEN_MES)
FROM SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_NARTD INFO SET INFO.VENTA_AA_TOTAL=(
SELECT SUM(VENTA_AA)
FROM SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_NARTD INFO SET INFO.VENTA_MA_TOTAL=(
SELECT SUM(VENTA_MA)
FROM SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_NARTD INFO SET INFO.VENTA_MES_TOTAL=(
SELECT SUM(VENTA_MES)
FROM SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_NARTD INFO SET INFO.VOLUMEN_YTD_TOTAL=(
SELECT SUM(VOLUMEN_YTD)
FROM SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_NARTD INFO SET INFO.VOLUMEN_YTD_AA_TOTAL=(
SELECT SUM(VOLUMEN_YTD_AA)
FROM SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_NARTD INFO SET INFO.VENTA_YTD_TOTAL=(
SELECT SUM(VENTA_YTD)
FROM SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_NARTD INFO SET INFO.VENTA_YTD_AA_TOTAL=(
SELECT SUM(VENTA_YTD_AA)
FROM SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** ELIMINAR TABLA TEMPORAL CALCULOS TOTALES *****/
DROP TABLE SHARE_CLAVECORTAPAIS_INFO_NARTD_TOTAL;


/****** ELIMINA REGISTROS EXISTENTES DE TABLA ST GRUPO DE CATEGORIA - CANAL**********/

DELETE FROM SHARE_ST_INFO_G_CANAL
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** INSERTA REGISTROS A TABLA ST **********/

INSERT INTO SHARE_ST_INFO_G_CANAL
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CANAL, FABRICANTE,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_AA_KOF) AS VOLUMEN_AA_KOF,
SUM(VOLUMEN_AA_TOTAL) AS VOLUMEN_AA_TOTAL,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_MA_KOF) AS VOLUMEN_MA_KOF,
SUM(VOLUMEN_MA_TOTAL) AS VOLUMEN_MA_TOTAL,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MES_KOF) AS VOLUMEN_MES_KOF,
SUM(VOLUMEN_MES_TOTAL) AS VOLUMEN_MES_TOTAL,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_AA_KOF) AS VENTA_AA_KOF,
SUM(VENTA_AA_TOTAL) AS VENTA_AA_TOTAL,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_MA_KOF) AS VENTA_MA_KOF,
SUM(VENTA_MA_TOTAL) AS VENTA_MA_TOTAL,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MES_KOF) AS VENTA_MES_KOF,
SUM(VENTA_MES_TOTAL) AS VENTA_MES_TOTAL,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS VOLUMEN_YTD_AA_KOF,
SUM(VOLUMEN_YTD_AA_TOTAL) AS VOLUMEN_YTD_AA_TOTAL,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_KOF) AS VOLUMEN_YTD_KOF,
SUM(VOLUMEN_YTD_TOTAL) AS VOLUMEN_YTD_TOTAL,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS VENTA_YTD_AA_KOF,
SUM(VENTA_YTD_AA_TOTAL) AS VENTA_YTD_AA_TOTAL,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_KOF) AS VENTA_YTD_KOF,
SUM(VENTA_YTD_TOTAL) AS VENTA_YTD_TOTAL
FROM SHARE_TMP_CLAVECORTAPAIS_INFO
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CANAL, FABRICANTE;
COMMIT;

/********************* SHARE - CALCULA LOS INDICADORES YTD,MA,AA TOTALES GRUPO CATEGORIA - CANAL **************************/

CREATE TABLE SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL AS
SELECT * FROM ( SELECT DISTINCT * FROM SHARE_TMP_CLAVECORTAPAIS_INFO
WHERE FABRICANTE LIKE '%TOTAL%');

UPDATE SHARE_ST_INFO_G_CANAL INFO SET INFO.VOLUMEN_AA_TOTAL=(
SELECT SUM(VOLUMEN_AA)
FROM SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CANAL INFO SET INFO.VOLUMEN_MA_TOTAL=(
SELECT SUM(VOLUMEN_MA)
FROM SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CANAL INFO SET INFO.VOLUMEN_MES_TOTAL=(
SELECT SUM(VOLUMEN_MES)
FROM SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CANAL INFO SET INFO.VENTA_AA_TOTAL=(
SELECT SUM(VENTA_AA)
FROM SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CANAL INFO SET INFO.VENTA_MA_TOTAL=(
SELECT SUM(VENTA_MA)
FROM SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CANAL INFO SET INFO.VENTA_MES_TOTAL=(
SELECT SUM(VENTA_MES)
FROM SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CANAL INFO SET INFO.VOLUMEN_YTD_TOTAL=(
SELECT SUM(VOLUMEN_YTD)
FROM SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CANAL INFO SET INFO.VOLUMEN_YTD_AA_TOTAL=(
SELECT SUM(VOLUMEN_YTD_AA)
FROM SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CANAL INFO SET INFO.VENTA_YTD_TOTAL=(
SELECT SUM(VENTA_YTD)
FROM SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CANAL INFO SET INFO.VENTA_YTD_AA_TOTAL=(
SELECT SUM(VENTA_YTD_AA)
FROM SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL
AND TMP.GRUPO_CATEGORIA = INFO.GRUPO_CATEGORIA)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** ELIMINAR TABLA TEMPORAL CALCULOS TOTALES *****/
DROP TABLE SHARE_CLAVECORTAPAIS_INFO_CANAL_TOTAL;


/****** ELIMINA REGISTROS EXISTENTES DE TABLA ST NARTD**********/

DELETE FROM SHARE_ST_INFO_CANAL_NARTD ST
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** INSERTA REGISTROS A TABLA ST **********/

INSERT INTO SHARE_ST_INFO_CANAL_NARTD
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, CANAL, FABRICANTE,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_AA_KOF) AS VOLUMEN_AA_KOF,
SUM(VOLUMEN_AA_TOTAL) AS VOLUMEN_AA_TOTAL,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_MA_KOF) AS VOLUMEN_MA_KOF,
SUM(VOLUMEN_MA_TOTAL) AS VOLUMEN_MA_TOTAL,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MES_KOF) AS VOLUMEN_MES_KOF,
SUM(VOLUMEN_MES_TOTAL) AS VOLUMEN_MES_TOTAL,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_AA_KOF) AS VENTA_AA_KOF,
SUM(VENTA_AA_TOTAL) AS VENTA_AA_TOTAL,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_MA_KOF) AS VENTA_MA_KOF,
SUM(VENTA_MA_TOTAL) AS VENTA_MA_TOTAL,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MES_KOF) AS VENTA_MES_KOF,
SUM(VENTA_MES_TOTAL) AS VENTA_MES_TOTAL,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS VOLUMEN_YTD_AA_KOF,
SUM(VOLUMEN_YTD_AA_TOTAL) AS VOLUMEN_YTD_AA_TOTAL,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_KOF) AS VOLUMEN_YTD_KOF,
SUM(VOLUMEN_YTD_TOTAL) AS VOLUMEN_YTD_TOTAL,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS VENTA_YTD_AA_KOF,
SUM(VENTA_YTD_AA_TOTAL) AS VENTA_YTD_AA_TOTAL,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_KOF) AS VENTA_YTD_KOF,
SUM(VENTA_YTD_TOTAL) AS VENTA_YTD_TOTAL
FROM SHARE_TMP_CLAVECORTAPAIS_INFO
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, CANAL, FABRICANTE;
COMMIT;


/********************* SHARE - CALCULA LOS INDICADORES YTD,MA,AA TOTALES NARTD **************************/

CREATE TABLE SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL AS
SELECT * FROM ( SELECT DISTINCT * FROM SHARE_TMP_CLAVECORTAPAIS_INFO
WHERE FABRICANTE LIKE '%TOTAL%');

UPDATE SHARE_ST_INFO_CANAL_NARTD INFO SET INFO.VOLUMEN_AA_TOTAL=(
SELECT SUM(VOLUMEN_AA)
FROM SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_NARTD INFO SET INFO.VOLUMEN_MA_TOTAL=(
SELECT SUM(VOLUMEN_MA)
FROM SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_NARTD INFO SET INFO.VOLUMEN_MES_TOTAL=(
SELECT SUM(VOLUMEN_MES)
FROM SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_NARTD INFO SET INFO.VENTA_AA_TOTAL=(
SELECT SUM(VENTA_AA)
FROM SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_NARTD INFO SET INFO.VENTA_MA_TOTAL=(
SELECT SUM(VENTA_MA)
FROM SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_NARTD INFO SET INFO.VENTA_MES_TOTAL=(
SELECT SUM(VENTA_MES)
FROM SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_NARTD INFO SET INFO.VOLUMEN_YTD_TOTAL=(
SELECT SUM(VOLUMEN_YTD)
FROM SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_NARTD INFO SET INFO.VOLUMEN_YTD_AA_TOTAL=(
SELECT SUM(VOLUMEN_YTD_AA)
FROM SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_NARTD INFO SET INFO.VENTA_YTD_TOTAL=(
SELECT SUM(VENTA_YTD)
FROM SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_NARTD INFO SET INFO.VENTA_YTD_AA_TOTAL=(
SELECT SUM(VENTA_YTD_AA)
FROM SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL TMP
WHERE TMP.FECHA = INFO.FECHA
AND TMP.PAIS = INFO.PAIS
AND TMP.CANAL = INFO.CANAL)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;


/****** ELIMINAR TABLA TEMPORAL CALCULOS TOTALES *****/
DROP TABLE SHARE_CLAVECORTAPAIS_CANAL_NARTD_TOTAL;
COMMIT;
