/********************* SHARE - INSERTA REGISTROS EN TABLA DE HECHOS Y AGREGADAS **************************/

/****** TRUNCA TABLA DE HECHOS **********/

TRUNCATE TABLE SHARE_FACT_INFO_MENSUAL;
COMMIT;

/****** RECREA SECUENCIAS **********/

DROP SEQUENCE SHARE_SEQ_PK_REG;

CREATE SEQUENCE SHARE_SEQ_PK_REG
START WITH 1
INCREMENT BY 1 
NOMAXVALUE ;

/****** INSERTA REGISTROS DE TABLA ST A TABLA DE HECHOS SHARE_FACT_INFO **********/

INSERT INTO SHARE_FACT_INFO_MENSUAL
SELECT 
  SHARE_SEQ_PK_REG.NEXTVAL,
  NVL(TIEMPO,0),
  NVL(PK_PAIS,0),
  NVL(PK_UNIDAD_NEGOCIO,0),
  NVL(PK_CANAL,0),
  NVL(PK_SUBCANAL,0),
  NVL(PK_UNIDAD_OPERATIVA,0),
  NVL(PK_REGION,0),
  NVL(PK_ZONA,0),
  NVL(PK_GRUPO_CATEGORIA,0),
  NVL(PK_CATEGORIA,0),
  NVL(PK_FABRICANTE,0),
  NVL(PK_MARCA,0),
  NVL(PK_SABOR,0),
  NVL(PK_TAMANO,0),
  NVL(PK_EMPAQUE,0),
  NVL(PK_RETORNABILIDAD,0),
  VOLUMEN_MES AS VOLUMEN_MES,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_MES ELSE NULL END AS VOLUMEN_MES_KOF,
  VOLUMEN_MA AS VOLUMEN_MA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_MA ELSE NULL END AS VOLUMEN_MA_KOF,
  VOLUMEN_AA AS VOLUMEN_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_AA ELSE NULL END AS VOLUMEN_AA_KOF,
  VOLUMEN_YTD AS VOLUMEN_YTD,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_YTD ELSE NULL END AS VOLUMEN_YTD_KOF,
  VOLUMEN_YTD_AA AS VOLUMEN_YTD_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_YTD_AA ELSE NULL END AS VOLUMEN_YTD_AA_KOF,
  VENTA_MES AS VENTA_MES,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_MES ELSE NULL END AS VENTA_MES_KOF,
  VENTA_MA AS VENTA_MA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_MA ELSE NULL END AS VENTA_MA_KOF,
   VENTA_AA AS VENTA_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_AA ELSE NULL END AS VENTA_AA_KOF,
  VENTA_YTD AS VENTA_YTD,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_YTD ELSE NULL END AS VENTA_YTD_KOF,
   VENTA_YTD_AA AS VENTA_YTD_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_YTD_AA ELSE NULL END AS VENTA_YTD_AA_KOF
FROM (SELECT  TIEMPO, PAIS, UNIDAD_NEGOCIO, CANAL, SUBCANAL, UNIDAD_OPERATIVA, REGION, ZONA, GRUPO_CATEGORIA, CATEGORIA, FABRICANTE,
MARCA, SABOR, TAMANO, EMPAQUE, RETORNABILIDAD,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA
FROM SHARE_ST_INFO GROUP BY  TIEMPO, PAIS, UNIDAD_NEGOCIO, CANAL, SUBCANAL, UNIDAD_OPERATIVA, REGION, ZONA, GRUPO_CATEGORIA, CATEGORIA, FABRICANTE,
MARCA, SABOR, TAMANO, EMPAQUE, RETORNABILIDAD)TMP
LEFT JOIN SHARE_DIM_PAIS DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_UNIDAD_NEGOCIO DU
ON TMP.UNIDAD_NEGOCIO=DU.GV_UNIDAD_NEGOCIO
LEFT JOIN SHARE_DIM_CANAL DC
ON TMP.CANAL=DC.GV_CANAL
LEFT JOIN SHARE_DIM_SUBCANAL DSC
ON TMP.SUBCANAL=DSC.GV_SUBCANAL
LEFT JOIN SHARE_DIM_UNIDAD_OPERATIVA DO
ON TMP.UNIDAD_OPERATIVA=DO.GV_UNIDAD_OPERATIVA
LEFT JOIN SHARE_DIM_REGION DR
ON TMP.REGION=DR.GV_REGION
LEFT JOIN SHARE_DIM_ZONA DZ
ON TMP.ZONA=DZ.GV_ZONA
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIA DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIA DCH
ON TMP.CATEGORIA=DCH.GV_CATEGORIA
LEFT JOIN SHARE_DIM_FABRICANTE DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE
LEFT JOIN SHARE_DIM_MARCA DM
ON TMP.MARCA=DM.GV_MARCA
LEFT JOIN SHARE_DIM_SABOR DS
ON TMP.SABOR=DS.GV_SABOR
LEFT JOIN SHARE_DIM_TAMANO DT
ON TMP.TAMANO=DT.GV_TAMANO
LEFT JOIN SHARE_DIM_EMPAQUE DE
ON TMP.EMPAQUE=DE.GV_EMPAQUE
LEFT JOIN SHARE_DIM_RETORNABILIDAD DR
ON TMP.RETORNABILIDAD=DR.GV_RETORNABILIDAD;
COMMIT;


/****** TRUNCA TABLAS AGREGADAS **********/

TRUNCATE TABLE SHARE_AGG_INFO_CANAL;
TRUNCATE TABLE SHARE_AGG_INFO_G_CAT;
TRUNCATE TABLE SHARE_AGG_INFO_CAT;


/****** RECREA SECUENCIAS **********/

DROP SEQUENCE SHARE_SEQ_AGG_REG_1;
DROP SEQUENCE SHARE_SEQ_AGG_REG_2;
DROP SEQUENCE SHARE_SEQ_AGG_REG_3;

CREATE SEQUENCE SHARE_SEQ_AGG_REG_1
START WITH 1
INCREMENT BY 1 
NOMAXVALUE ;

CREATE SEQUENCE SHARE_SEQ_AGG_REG_2
START WITH 1
INCREMENT BY 1 
NOMAXVALUE ;

CREATE SEQUENCE SHARE_SEQ_AGG_REG_3
START WITH 1
INCREMENT BY 1 
NOMAXVALUE ;

/****** INSERTA REGISTROS DE TABLA ST A TABLA DE HECHOS SHARE_FACT_INFO **********/

INSERT INTO SHARE_AGG_INFO_CANAL
SELECT 
  SHARE_SEQ_AGG_REG_1.NEXTVAL,
  NVL(TIEMPO,0), 
  NVL(PK_PAIS,0), 
  NVL(PK_GRUPO_CATEGORIA,0),
  NVL(PK_CATEGORIA,0),
  NVL(PK_UNIDAD_NEGOCIO,0),
  NVL(PK_FABRICANTE,0),
  VOLUMEN_MES AS VOLUMEN_MES,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_MES ELSE NULL END AS VOLUMEN_MES_KOF,
  VOLUMEN_MA AS VOLUMEN_MA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_MA ELSE NULL END AS VOLUMEN_MA_KOF,
  VOLUMEN_AA AS VOLUMEN_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_AA ELSE NULL END AS VOLUMEN_AA_KOF,
  VOLUMEN_YTD AS VOLUMEN_YTD,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_YTD ELSE NULL END AS VOLUMEN_YTD_KOF,
  VOLUMEN_YTD_AA AS VOLUMEN_YTD_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_YTD_AA ELSE NULL END AS VOLUMEN_YTD_AA_KOF,
  VENTA_MES AS VENTA_MES,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_MES ELSE NULL END AS VENTA_MES_KOF,
  VENTA_MA AS VENTA_MA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_MA ELSE NULL END AS VENTA_MA_KOF,
   VENTA_AA AS VENTA_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_AA ELSE NULL END AS VENTA_AA_KOF,
  VENTA_YTD AS VENTA_YTD,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_YTD ELSE NULL END AS VENTA_YTD_KOF,
   VENTA_YTD_AA AS VENTA_YTD_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_YTD_AA ELSE NULL END AS VENTA_YTD_AA_KOF
FROM 
(SELECT  TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, UNIDAD_NEGOCIO, FABRICANTE,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA
FROM SHARE_ST_INFO GROUP BY  TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, UNIDAD_NEGOCIO, FABRICANTE)TMP
LEFT JOIN SHARE_DIM_PAIS DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIA DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIA DCH
ON TMP.CATEGORIA=DCH.GV_CATEGORIA
LEFT JOIN SHARE_DIM_UNIDAD_NEGOCIO DU
ON TMP.UNIDAD_NEGOCIO=DU.GV_UNIDAD_NEGOCIO
LEFT JOIN SHARE_DIM_FABRICANTE DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE;
COMMIT;


INSERT INTO SHARE_AGG_INFO_G_CAT
SELECT 
  SHARE_SEQ_AGG_REG_2.NEXTVAL,
  NVL(TIEMPO,0), 
  NVL(PK_PAIS,0), 
  NVL(PK_GRUPO_CATEGORIA,0),
  NVL(PK_FABRICANTE,0),
  VOLUMEN_MES AS VOLUMEN_MES,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_MES ELSE NULL END AS VOLUMEN_MES_KOF,
  VOLUMEN_MA AS VOLUMEN_MA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_MA ELSE NULL END AS VOLUMEN_MA_KOF,
  VOLUMEN_AA AS VOLUMEN_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_AA ELSE NULL END AS VOLUMEN_AA_KOF,
  VOLUMEN_YTD AS VOLUMEN_YTD,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_YTD ELSE NULL END AS VOLUMEN_YTD_KOF,
  VOLUMEN_YTD_AA AS VOLUMEN_YTD_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_YTD_AA ELSE NULL END AS VOLUMEN_YTD_AA_KOF,
  VENTA_MES AS VENTA_MES,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_MES ELSE NULL END AS VENTA_MES_KOF,
  VENTA_MA AS VENTA_MA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_MA ELSE NULL END AS VENTA_MA_KOF,
   VENTA_AA AS VENTA_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_AA ELSE NULL END AS VENTA_AA_KOF,
  VENTA_YTD AS VENTA_YTD,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_YTD ELSE NULL END AS VENTA_YTD_KOF,
   VENTA_YTD_AA AS VENTA_YTD_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_YTD_AA ELSE NULL END AS VENTA_YTD_AA_KOF
FROM 
(SELECT  TIEMPO, PAIS, GRUPO_CATEGORIA, FABRICANTE,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA
FROM SHARE_ST_INFO GROUP BY  TIEMPO, PAIS, GRUPO_CATEGORIA, FABRICANTE)TMP
LEFT JOIN SHARE_DIM_PAIS DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIA DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_FABRICANTE DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE;
COMMIT;


INSERT INTO SHARE_AGG_INFO_CAT
SELECT 
  SHARE_SEQ_AGG_REG_3.NEXTVAL,
  NVL(TIEMPO,0), 
  NVL(PK_PAIS,0), 
  NVL(PK_GRUPO_CATEGORIA,0),
  NVL(PK_CATEGORIA,0),
  NVL(PK_FABRICANTE,0),
  VOLUMEN_MES AS VOLUMEN_MES,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_MES ELSE NULL END AS VOLUMEN_MES_KOF,
  VOLUMEN_MA AS VOLUMEN_MA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_MA ELSE NULL END AS VOLUMEN_MA_KOF,
  VOLUMEN_AA AS VOLUMEN_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_AA ELSE NULL END AS VOLUMEN_AA_KOF,
  VOLUMEN_YTD AS VOLUMEN_YTD,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_YTD ELSE NULL END AS VOLUMEN_YTD_KOF,
  VOLUMEN_YTD_AA AS VOLUMEN_YTD_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VOLUMEN_YTD_AA ELSE NULL END AS VOLUMEN_YTD_AA_KOF,
  VENTA_MES AS VENTA_MES,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_MES ELSE NULL END AS VENTA_MES_KOF,
  VENTA_MA AS VENTA_MA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_MA ELSE NULL END AS VENTA_MA_KOF,
   VENTA_AA AS VENTA_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_AA ELSE NULL END AS VENTA_AA_KOF,
  VENTA_YTD AS VENTA_YTD,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_YTD ELSE NULL END AS VENTA_YTD_KOF,
   VENTA_YTD_AA AS VENTA_YTD_AA,
  CASE WHEN FABRICANTE LIKE'%KOF%' OR FABRICANTE LIKE'%FEMSA%' THEN VENTA_YTD_AA ELSE NULL END AS VENTA_YTD_AA_KOF
FROM 
(SELECT  TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, FABRICANTE,
SUM(VOLUMEN_MES) AS VOLUMEN_MES,
SUM(VOLUMEN_MA) AS VOLUMEN_MA,
SUM(VOLUMEN_AA) AS VOLUMEN_AA,
SUM(VOLUMEN_YTD) AS VOLUMEN_YTD,
SUM(VOLUMEN_YTD_AA) AS VOLUMEN_YTD_AA,
SUM(VENTA_MES) AS VENTA_MES,
SUM(VENTA_MA) AS VENTA_MA,
SUM(VENTA_AA) AS VENTA_AA,
SUM(VENTA_YTD) AS VENTA_YTD,
SUM(VENTA_YTD_AA) AS VENTA_YTD_AA
FROM SHARE_ST_INFO GROUP BY  TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, FABRICANTE)TMP
LEFT JOIN SHARE_DIM_PAIS DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIA DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIA DCH
ON TMP.CATEGORIA=DCH.GV_CATEGORIA
LEFT JOIN SHARE_DIM_FABRICANTE DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE;
COMMIT;

EXIT;

