/********************* SHARE - INSERTA REGISTROS EN TABLA DE HECHOS **************************/

/****** TRUNCA TABLA DE HECHOS Y AGREGADAS **********/

TRUNCATE TABLE SHARE_FACT_INFO;
TRUNCATE TABLE SHARE_AGG_INFO_CAT;
TRUNCATE TABLE SHARE_AGG_INFO_CANAL;
TRUNCATE TABLE SHARE_AGG_INFO_G_CAT;
TRUNCATE TABLE SHARE_AGG_INFO_NARTD;
TRUNCATE TABLE SHARE_AGG_INFO_G_CANAL;
TRUNCATE TABLE SHARE_AGG_INFO_CANAL_NARTD;

/****** RECREA SECUENCIAS **********/

DROP SEQUENCE SEQ_PK_REG_SHARE;
DROP SEQUENCE SEQ_AGG_REG_SHARE_1;
DROP SEQUENCE SEQ_AGG_REG_SHARE_2;
DROP SEQUENCE SEQ_AGG_REG_SHARE_3;
DROP SEQUENCE SEQ_AGG_REG_SHARE_4;
DROP SEQUENCE SEQ_AGG_REG_SHARE_5;
DROP SEQUENCE SEQ_AGG_REG_SHARE_6;

CREATE SEQUENCE SEQ_PK_REG_SHARE
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_1
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_2
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_3
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_4
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_5
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_6
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;


/****** INSERTA REGISTROS A TABLA DE HECHOS SHARE_FACT_INFO **********/

INSERT INTO SHARE_FACT_INFO
SELECT
SEQ_PK_REG_SHARE.NEXTVAL,
ID_TIEMPO,
PK_PAIS,
PK_GRUPO_CATEGORIA,
PK_CATEGORIA,
PK_CANAL,
PK_FABRICANTE,
VOLUMEN_AA,
VOLUMEN_AA_KOF,
VOLUMEN_AA_TOTAL,
VOLUMEN_MA,
VOLUMEN_MA_KOF,
VOLUMEN_MA_TOTAL,
VOLUMEN_MES,
VOLUMEN_MES_KOF,
VOLUMEN_MES_TOTAL,
VENTA_AA,
VENTA_AA_KOF,
VENTA_AA_TOTAL,
VENTA_MA,
VENTA_MA_KOF,
VENTA_MA_TOTAL,
VENTA_MES,
VENTA_MES_KOF,
VENTA_MES_TOTAL,
VOLUMEN_YTD_AA,
VOLUMEN_YTD_AA_KOF,
VOLUMEN_YTD_AA_TOTAL,
VOLUMEN_YTD,
VOLUMEN_YTD_KOF,
VOLUMEN_YTD_TOTAL,
VENTA_YTD_AA,
VENTA_YTD_AA_KOF,
VENTA_YTD_AA_TOTAL,
VENTA_YTD,
VENTA_YTD_KOF,
VENTA_YTD_TOTAL
FROM SHARE_ST_INFO_FAB TMP
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES = UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIAS DC
ON TMP.CATEGORIA=DC.GV_CATEGORIA
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE
LEFT JOIN SHARE_DIM_CANALES DCAN
ON TMP.CANAL=DCAN.GV_CANAL
WHERE TMP.FABRICANTE NOT LIKE '%TOTAL%';
COMMIT;

/****** INSERTA REGISTROS A TABLA AGREGADA CATEGORIA  **********/

INSERT INTO SHARE_AGG_INFO_CAT
SELECT
SEQ_AGG_REG_SHARE_1.NEXTVAL,
ID_TIEMPO,
PK_PAIS,
PK_GRUPO_CATEGORIA,
PK_CATEGORIA,
PK_FABRICANTE,
VOLUMEN_AA,
VOLUMEN_AA_KOF,
VOLUMEN_AA_TOTAL,
VOLUMEN_MA,
VOLUMEN_MA_KOF,
VOLUMEN_MA_TOTAL,
VOLUMEN_MES,
VOLUMEN_MES_KOF,
VOLUMEN_MES_TOTAL,
VENTA_AA,
VENTA_AA_KOF,
VENTA_AA_TOTAL,
VENTA_MA,
VENTA_MA_KOF,
VENTA_MA_TOTAL,
VENTA_MES,
VENTA_MES_KOF,
VENTA_MES_TOTAL,
VOLUMEN_YTD_AA,
VOLUMEN_YTD_AA_KOF,
VOLUMEN_YTD_AA_TOTAL,
VOLUMEN_YTD,
VOLUMEN_YTD_KOF,
VOLUMEN_YTD_TOTAL,
VENTA_YTD_AA,
VENTA_YTD_AA_KOF,
VENTA_YTD_AA_TOTAL,
VENTA_YTD,
VENTA_YTD_KOF,
VENTA_YTD_TOTAL
FROM SHARE_ST_INFO_CAT TMP
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES = UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIAS DC
ON TMP.CATEGORIA=DC.GV_CATEGORIA
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE
WHERE TMP.FABRICANTE NOT LIKE '%TOTAL%';
COMMIT;

/****** INSERTA REGISTROS A TABLA AGREGADA CANAL  **********/

INSERT INTO SHARE_AGG_INFO_CANAL
SELECT
SEQ_AGG_REG_SHARE_2.NEXTVAL,
ID_TIEMPO,
PK_PAIS,
PK_GRUPO_CATEGORIA,
PK_CATEGORIA,
PK_CANAL,
PK_FABRICANTE,
VOLUMEN_AA,
VOLUMEN_AA_KOF,
VOLUMEN_AA_TOTAL,
VOLUMEN_MA,
VOLUMEN_MA_KOF,
VOLUMEN_MA_TOTAL,
VOLUMEN_MES,
VOLUMEN_MES_KOF,
VOLUMEN_MES_TOTAL,
VENTA_AA,
VENTA_AA_KOF,
VENTA_AA_TOTAL,
VENTA_MA,
VENTA_MA_KOF,
VENTA_MA_TOTAL,
VENTA_MES,
VENTA_MES_KOF,
VENTA_MES_TOTAL,
VOLUMEN_YTD_AA,
VOLUMEN_YTD_AA_KOF,
VOLUMEN_YTD_AA_TOTAL,
VOLUMEN_YTD,
VOLUMEN_YTD_KOF,
VOLUMEN_YTD_TOTAL,
VENTA_YTD_AA,
VENTA_YTD_AA_KOF,
VENTA_YTD_AA_TOTAL,
VENTA_YTD,
VENTA_YTD_KOF,
VENTA_YTD_TOTAL
FROM SHARE_ST_INFO_CANAL TMP
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES = UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIAS DC
ON TMP.CATEGORIA=DC.GV_CATEGORIA
LEFT JOIN SHARE_DIM_CANALES DCAN
ON TMP.CANAL=DCAN.GV_CANAL
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE
WHERE TMP.FABRICANTE NOT LIKE '%TOTAL%';
COMMIT;


/****** INSERTA REGISTROS A TABLA AGREGADA G_CATEGORIA  **********/

INSERT INTO SHARE_AGG_INFO_G_CAT
SELECT
SEQ_AGG_REG_SHARE_3.NEXTVAL,
ID_TIEMPO,
PK_PAIS,
PK_GRUPO_CATEGORIA,
PK_FABRICANTE,
VOLUMEN_AA,
VOLUMEN_AA_KOF,
VOLUMEN_AA_TOTAL,
VOLUMEN_MA,
VOLUMEN_MA_KOF,
VOLUMEN_MA_TOTAL,
VOLUMEN_MES,
VOLUMEN_MES_KOF,
VOLUMEN_MES_TOTAL,
VENTA_AA,
VENTA_AA_KOF,
VENTA_AA_TOTAL,
VENTA_MA,
VENTA_MA_KOF,
VENTA_MA_TOTAL,
VENTA_MES,
VENTA_MES_KOF,
VENTA_MES_TOTAL,
VOLUMEN_YTD_AA,
VOLUMEN_YTD_AA_KOF,
VOLUMEN_YTD_AA_TOTAL,
VOLUMEN_YTD,
VOLUMEN_YTD_KOF,
VOLUMEN_YTD_TOTAL,
VENTA_YTD_AA,
VENTA_YTD_AA_KOF,
VENTA_YTD_AA_TOTAL,
VENTA_YTD,
VENTA_YTD_KOF,
VENTA_YTD_TOTAL
FROM SHARE_ST_INFO_G_CAT TMP
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES = UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE
WHERE TMP.FABRICANTE NOT LIKE '%TOTAL%';
COMMIT;

/****** INSERTA REGISTROS A TABLA AGREGADA NARTD **********/

INSERT INTO SHARE_AGG_INFO_NARTD
SELECT
SEQ_AGG_REG_SHARE_4.NEXTVAL,
ID_TIEMPO,
PK_PAIS,
PK_FABRICANTE,
VOLUMEN_AA,
VOLUMEN_AA_KOF,
VOLUMEN_AA_TOTAL,
VOLUMEN_MA,
VOLUMEN_MA_KOF,
VOLUMEN_MA_TOTAL,
VOLUMEN_MES,
VOLUMEN_MES_KOF,
VOLUMEN_MES_TOTAL,
VENTA_AA,
VENTA_AA_KOF,
VENTA_AA_TOTAL,
VENTA_MA,
VENTA_MA_KOF,
VENTA_MA_TOTAL,
VENTA_MES,
VENTA_MES_KOF,
VENTA_MES_TOTAL,
VOLUMEN_YTD_AA,
VOLUMEN_YTD_AA_KOF,
VOLUMEN_YTD_AA_TOTAL,
VOLUMEN_YTD,
VOLUMEN_YTD_KOF,
VOLUMEN_YTD_TOTAL,
VENTA_YTD_AA,
VENTA_YTD_AA_KOF,
VENTA_YTD_AA_TOTAL,
VENTA_YTD,
VENTA_YTD_KOF,
VENTA_YTD_TOTAL
FROM SHARE_ST_INFO_NARTD TMP
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES = UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE
WHERE TMP.FABRICANTE NOT LIKE '%TOTAL%';
COMMIT;

/****** INSERTA REGISTROS A TABLA AGREGADA GRUPO CATEGORIA - CANAL  **********/

INSERT INTO SHARE_AGG_INFO_G_CANAL
SELECT
SEQ_AGG_REG_SHARE_5.NEXTVAL,
ID_TIEMPO,
PK_PAIS,
PK_GRUPO_CATEGORIA,
PK_CANAL,
PK_FABRICANTE,
VOLUMEN_AA,
VOLUMEN_AA_KOF,
VOLUMEN_AA_TOTAL,
VOLUMEN_MA,
VOLUMEN_MA_KOF,
VOLUMEN_MA_TOTAL,
VOLUMEN_MES,
VOLUMEN_MES_KOF,
VOLUMEN_MES_TOTAL,
VENTA_AA,
VENTA_AA_KOF,
VENTA_AA_TOTAL,
VENTA_MA,
VENTA_MA_KOF,
VENTA_MA_TOTAL,
VENTA_MES,
VENTA_MES_KOF,
VENTA_MES_TOTAL,
VOLUMEN_YTD_AA,
VOLUMEN_YTD_AA_KOF,
VOLUMEN_YTD_AA_TOTAL,
VOLUMEN_YTD,
VOLUMEN_YTD_KOF,
VOLUMEN_YTD_TOTAL,
VENTA_YTD_AA,
VENTA_YTD_AA_KOF,
VENTA_YTD_AA_TOTAL,
VENTA_YTD,
VENTA_YTD_KOF,
VENTA_YTD_TOTAL
FROM SHARE_ST_INFO_G_CANAL TMP
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES = UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CANALES DCAN
ON TMP.CANAL=DCAN.GV_CANAL
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE
WHERE TMP.FABRICANTE NOT LIKE '%TOTAL%';
COMMIT;

/****** INSERTA REGISTROS A TABLA AGREGADA CANAL - NARTD **********/

INSERT INTO SHARE_AGG_INFO_CANAL_NARTD
SELECT
SEQ_AGG_REG_SHARE_6.NEXTVAL,
ID_TIEMPO,
PK_PAIS,
PK_CANAL,
PK_FABRICANTE,
VOLUMEN_AA,
VOLUMEN_AA_KOF,
VOLUMEN_AA_TOTAL,
VOLUMEN_MA,
VOLUMEN_MA_KOF,
VOLUMEN_MA_TOTAL,
VOLUMEN_MES,
VOLUMEN_MES_KOF,
VOLUMEN_MES_TOTAL,
VENTA_AA,
VENTA_AA_KOF,
VENTA_AA_TOTAL,
VENTA_MA,
VENTA_MA_KOF,
VENTA_MA_TOTAL,
VENTA_MES,
VENTA_MES_KOF,
VENTA_MES_TOTAL,
VOLUMEN_YTD_AA,
VOLUMEN_YTD_AA_KOF,
VOLUMEN_YTD_AA_TOTAL,
VOLUMEN_YTD,
VOLUMEN_YTD_KOF,
VOLUMEN_YTD_TOTAL,
VENTA_YTD_AA,
VENTA_YTD_AA_KOF,
VENTA_YTD_AA_TOTAL,
VENTA_YTD,
VENTA_YTD_KOF,
VENTA_YTD_TOTAL
FROM SHARE_ST_INFO_CANAL_NARTD TMP
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES = UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_CANALES DCAN
ON TMP.CANAL=DCAN.GV_CANAL
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE
WHERE TMP.FABRICANTE NOT LIKE '%TOTAL%';
COMMIT;
