/********************* SHARE - INSERTA REGISTROS EN TABLAS DASHBOARD ST   **************************/

/****** ELIMINA REGISTROS EXISTENTES DE TABLA DASHBOARD ST GRUPO DE CATEGORIA**********/

DELETE FROM SHARE_ST_INFO_G_CAT_DASH ST
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/********** INSERTA REGISTROS VOLUMEN Y VENTA A TABLA GRUPO DE CATEGORIA ST DASHBOARD **********/

INSERT INTO SHARE_ST_INFO_G_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
SUM(VOLUMEN_AA) AS INDICADOR_AA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES) AS INDICADOR_MES,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD) AS INDICADOR_YTD_MES,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_G_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET  NIVEL = 'KOF',INDICADOR = 'SOM'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_G_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
INDICADOR_AA_KOF,
INDICADOR_MES_KOF,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_G_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET NIVEL = 'NARTD', INDICADOR = 'SOM'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH INFO SET INFO.INDICADOR_MES=(
SELECT SUM(VOLUMEN_MES)
FROM SHARE_ST_INFO_G_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH INFO SET INFO.INDICADOR_AA=(
SELECT SUM(VOLUMEN_AA)
FROM SHARE_ST_INFO_G_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH INFO SET INFO.INDICADOR_YTD_MES=(
SELECT SUM(VOLUMEN_YTD)
FROM SHARE_ST_INFO_G_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH INFO SET INFO.INDICADOR_YTD_AA=(
SELECT SUM(VOLUMEN_YTD_AA)
FROM SHARE_ST_INFO_G_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;
-------------- CALCULO NARTD - PAIS --------------

INSERT INTO SHARE_ST_INFO_G_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS,
SUM(VOLUMEN_AA) AS INDICADOR_AA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES) AS INDICADOR_MES,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD) AS INDICADOR_YTD_MES,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_G_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS;
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET INDICADOR = 'SOM', NIVEL = 'KOF'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_G_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS,
SUM(VOLUMEN_AA) AS INDICADOR_AA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES) AS INDICADOR_MES,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD) AS INDICADOR_YTD_MES,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_G_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS;
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET INDICADOR = 'SOM', NIVEL = 'NARTD'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;
-------------------------------------------------
-------------------------------------------------

INSERT INTO SHARE_ST_INFO_G_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_G_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET NIVEL = 'KOF', INDICADOR = 'SOS'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_G_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_G_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET NIVEL = 'NARTD', INDICADOR = 'SOS'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH INFO SET INFO.INDICADOR_MES=(
SELECT SUM(VENTA_MES)
FROM SHARE_ST_INFO_G_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH INFO SET INFO.INDICADOR_AA=(
SELECT SUM(VENTA_AA)
FROM SHARE_ST_INFO_G_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH INFO SET INFO.INDICADOR_YTD_MES=(
SELECT SUM(VENTA_YTD)
FROM SHARE_ST_INFO_G_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH INFO SET INFO.INDICADOR_YTD_AA=(
SELECT SUM(VENTA_YTD_AA)
FROM SHARE_ST_INFO_G_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

-------------- CALCULO NARTD - PAIS --------------

INSERT INTO SHARE_ST_INFO_G_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_G_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS;
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET NIVEL = 'KOF', INDICADOR = 'SOS'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_G_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_G_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS;
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET NIVEL = 'NARTD', INDICADOR = 'SOS'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

-------------------------------------------------
/****** CALCULA VALORES PARA SOM Y SOS  ******/

UPDATE SHARE_ST_INFO_G_CAT_DASH SET CALCULO_AA= Decode(INDICADOR_AA,0,0,((INDICADOR_AA_KOF)/(INDICADOR_AA))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET CALCULO_MES= Decode(INDICADOR_MES,0,0,((INDICADOR_MES_KOF)/(INDICADOR_MES))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET CALCULO_YTD_AA= Decode(INDICADOR_YTD_AA,0,0,((INDICADOR_YTD_AA_KOF)/(INDICADOR_YTD_AA))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET CALCULO_YTD_MES= Decode(INDICADOR_YTD_MES,0,0,((INDICADOR_YTD_MES_KOF)/(INDICADOR_YTD_MES))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** CALCULA VARIACIONES PP ******/

UPDATE SHARE_ST_INFO_G_CAT_DASH SET VARIACION_PP= CALCULO_MES-CALCULO_AA
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_G_CAT_DASH SET VARIACION_YTD_PP= CALCULO_YTD_MES-CALCULO_YTD_AA
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------

/****** ELIMINA REGISTROS EXISTENTES DE TABLA DASHBOARD ST CATEGORIA **********/

DELETE FROM SHARE_ST_INFO_CAT_DASH ST
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/********** INSERTA REGISTROS VOLUMEN Y VENTA A TABLA CATEGORIA ST DASHBOARD **********/

INSERT INTO SHARE_ST_INFO_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA,
SUM(VOLUMEN_AA) AS INDICADOR_AA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES) AS INDICADOR_MES,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD) AS INDICADOR_YTD_MES,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET NIVEL = 'KOF', INDICADOR = 'SOM'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA,
INDICADOR_AA_KOF,
INDICADOR_MES_KOF,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET NIVEL = 'NARTD', INDICADOR = 'SOM'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

-------------- CALCULO G_CATEGORIA --------------

INSERT INTO SHARE_ST_INFO_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
SUM(VOLUMEN_AA) AS INDICADOR_AA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES) AS INDICADOR_MES,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD) AS INDICADOR_YTD_MES,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA;
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET NIVEL = 'KOF', INDICADOR = 'SOM'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
INDICADOR_AA_KOF,
INDICADOR_MES_KOF,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA;
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET NIVEL = 'NARTD', INDICADOR = 'SOM'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH INFO SET INFO.INDICADOR_MES=(
SELECT SUM(VOLUMEN_MES)
FROM SHARE_ST_INFO_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH INFO SET INFO.INDICADOR_AA=(
SELECT SUM(VOLUMEN_AA)
FROM SHARE_ST_INFO_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH INFO SET INFO.INDICADOR_YTD_MES=(
SELECT SUM(VOLUMEN_YTD)
FROM SHARE_ST_INFO_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH INFO SET INFO.INDICADOR_YTD_AA=(
SELECT SUM(VOLUMEN_YTD_AA)
FROM SHARE_ST_INFO_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

------------------------------------------------------------------------------
------------------------------------------------------------------------------

INSERT INTO SHARE_ST_INFO_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET NIVEL = 'KOF', INDICADOR = 'SOS'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA,
INDICADOR_AA_KOF,
INDICADOR_MES_KOF,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES
FROM SHARE_ST_INFO_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET NIVEL = 'NARTD', INDICADOR = 'SOS'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

-------------- CALCULO G_CATEGORIA --------------

INSERT INTO SHARE_ST_INFO_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA;
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET INDICADOR = 'SOS', NIVEL = 'KOF'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CAT_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
INDICADOR_AA_KOF,
INDICADOR_MES_KOF,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CAT
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA;
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET INDICADOR = 'SOS', NIVEL = 'NARTD'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH INFO SET INFO.INDICADOR_MES=(
SELECT SUM(VENTA_MES)
FROM SHARE_ST_INFO_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH INFO SET INFO.INDICADOR_AA=(
SELECT SUM(VENTA_AA)
FROM SHARE_ST_INFO_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH INFO SET INFO.INDICADOR_YTD_MES=(
SELECT SUM(VENTA_YTD)
FROM SHARE_ST_INFO_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH INFO SET INFO.INDICADOR_YTD_AA=(
SELECT SUM(VENTA_YTD_AA)
FROM SHARE_ST_INFO_CAT TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;
-------------------------------------------------
-------------------------------------------------


/****** CALCULA VALORES PARA SOM Y SOS  ******/

UPDATE SHARE_ST_INFO_CAT_DASH SET CALCULO_AA = Decode(INDICADOR_AA,0,0,((INDICADOR_AA_KOF)/(INDICADOR_AA))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET CALCULO_MES = Decode(INDICADOR_MES,0,0,((INDICADOR_MES_KOF)/(INDICADOR_MES))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET CALCULO_YTD_AA = Decode(INDICADOR_YTD_AA,0,0,((INDICADOR_YTD_AA_KOF)/(INDICADOR_YTD_AA))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET CALCULO_YTD_MES = Decode(INDICADOR_YTD_MES,0,0,((INDICADOR_YTD_MES_KOF)/(INDICADOR_YTD_MES))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

/****** CALCULA VARIACIONES PP ******/

UPDATE SHARE_ST_INFO_CAT_DASH SET VARIACION_PP = CALCULO_MES-CALCULO_AA
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CAT_DASH SET VARIACION_YTD_PP = CALCULO_YTD_MES-CALCULO_YTD_AA
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------

/********** INSERTA REGISTROS VOLUMEN Y VENTA A TABLA CANAL ST DASHBOARD **********/

/****** ELIMINA REGISTROS EXISTENTES DE TABLA DASHBOARD ST CANAL **********/

DELETE FROM SHARE_ST_INFO_CANAL_DASH ST
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL,
SUM(VOLUMEN_AA) AS INDICADOR_AA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES) AS INDICADOR_MES,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD) AS INDICADOR_YTD_MES,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL, FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET NIVEL = 'KOF', INDICADOR = 'SOM'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL,
INDICADOR_AA_KOF,
INDICADOR_MES_KOF,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL, FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET NIVEL = 'NARTD', INDICADOR = 'SOM'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

-------------- CALCULO G_CATEGORIA - CANAL --------------

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CANAL,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,CANAL,
SUM(VOLUMEN_AA) AS INDICADOR_AA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES) AS INDICADOR_MES,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD) AS INDICADOR_YTD_MES,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CANAL;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET INDICADOR = 'SOM', NIVEL = 'KOF'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CANAL,
INDICADOR_AA_KOF,
INDICADOR_MES_KOF,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,CANAL,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CANAL;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET INDICADOR = 'SOM', NIVEL = 'NARTD'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH INFO SET INFO.INDICADOR_MES=(
SELECT SUM(VOLUMEN_MES)
FROM SHARE_ST_INFO_CANAL TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.CANAL = INFO.CANAL AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH INFO SET INFO.INDICADOR_AA=(
SELECT SUM(VOLUMEN_AA)
FROM SHARE_ST_INFO_CANAL TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.CANAL = INFO.CANAL AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH INFO SET INFO.INDICADOR_YTD_MES=(
SELECT SUM(VOLUMEN_YTD)
FROM SHARE_ST_INFO_CANAL TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.CANAL = INFO.CANAL AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH INFO SET INFO.INDICADOR_YTD_AA=(
SELECT SUM(VOLUMEN_YTD_AA)
FROM SHARE_ST_INFO_CANAL TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.CANAL = INFO.CANAL AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOM' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

-------------------------------------------------

-------------- CALCULO NARTD - CANAL ------------

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, CANAL,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, CANAL,
SUM(VOLUMEN_AA) AS INDICADOR_AA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES) AS INDICADOR_MES,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD) AS INDICADOR_YTD_MES,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, CANAL;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET INDICADOR = 'SOM', NIVEL = 'KOF'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, CANAL,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, CANAL,
SUM(VOLUMEN_AA) AS INDICADOR_AA,
SUM(VOLUMEN_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VOLUMEN_MES) AS INDICADOR_MES,
SUM(VOLUMEN_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VOLUMEN_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VOLUMEN_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VOLUMEN_YTD) AS INDICADOR_YTD_MES,
SUM(VOLUMEN_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, CANAL;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET INDICADOR = 'SOM', NIVEL = 'NARTD'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;
-------------------------------------------------
-------------------------------------------------

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL,FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET INDICADOR = 'SOS', NIVEL = 'KOF'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL,
INDICADOR_AA_KOF,
INDICADOR_MES_KOF,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA, CATEGORIA, CANAL,FABRICANTE;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET INDICADOR = 'SOS', NIVEL = 'NARTD'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

-------------- CALCULO G_CATEGORIA --------------

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,CANAL,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,CANAL,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,CANAL;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET INDICADOR = 'SOS', NIVEL = 'KOF'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,CANAL,
INDICADOR_AA_KOF,
INDICADOR_MES_KOF,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,CANAL,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, GRUPO_CATEGORIA,CANAL;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET INDICADOR = 'SOS', NIVEL = 'NARTD'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;
-------------------------------------------------

-------------- CALCULO NARTD - CANAL --------------

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, CANAL,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, CANAL,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, CANAL;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET INDICADOR = 'SOS', NIVEL = 'KOF'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

INSERT INTO SHARE_ST_INFO_CANAL_DASH
(FECHA, ANIO, MES, TIEMPO, PAIS, CANAL,
INDICADOR_AA, INDICADOR_AA_KOF,
INDICADOR_MES, INDICADOR_MES_KOF,
INDICADOR_YTD_AA, INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_MES, INDICADOR_YTD_MES_KOF)
SELECT FECHA, ANIO, MES, TIEMPO, PAIS, CANAL,
SUM(VENTA_AA) AS INDICADOR_AA,
SUM(VENTA_AA_KOF) AS INDICADOR_AA_KOF,
SUM(VENTA_MES) AS INDICADOR_MES,
SUM(VENTA_MES_KOF) AS INDICADOR_MES_KOF,
SUM(VENTA_YTD_AA) AS INDICADOR_YTD_AA,
SUM(VENTA_YTD_AA_KOF) AS INDICADOR_YTD_AA_KOF,
SUM(VENTA_YTD) AS INDICADOR_YTD_MES,
SUM(VENTA_YTD_KOF) AS INDICADOR_YTD_MES_KOF
FROM SHARE_ST_INFO_CANAL
WHERE FABRICANTE = 'TOTAL' AND PAIS = 'NOMBREPAIS'
GROUP BY FECHA, ANIO, MES, TIEMPO, PAIS, CANAL;
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET INDICADOR = 'SOS', NIVEL = 'NARTD'
WHERE INDICADOR IS NULL AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH INFO SET INFO.INDICADOR_MES=(
SELECT SUM(VENTA_MES)
FROM SHARE_ST_INFO_CANAL TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.CANAL = INFO.CANAL AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH INFO SET INFO.INDICADOR_AA=(
SELECT SUM(VENTA_AA)
FROM SHARE_ST_INFO_CANAL TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.CANAL = INFO.CANAL AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH INFO SET INFO.INDICADOR_YTD_MES=(
SELECT SUM(VENTA_YTD)
FROM SHARE_ST_INFO_CANAL TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.CANAL = INFO.CANAL AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH INFO SET INFO.INDICADOR_YTD_AA=(
SELECT SUM(VENTA_YTD_AA)
FROM SHARE_ST_INFO_CANAL TMP
WHERE TMP.FECHA = INFO.FECHA AND TMP.PAIS = INFO.PAIS AND TMP.CANAL = INFO.CANAL AND TMP.FABRICANTE = 'TOTAL')
WHERE INFO.INDICADOR = 'SOS' AND INFO.NIVEL = 'NARTD' AND PAIS = 'NOMBREPAIS';
COMMIT;

-------------------------------------------------

/****** CALCULA VALORES PARA SOM Y SOS  ******/

UPDATE SHARE_ST_INFO_CANAL_DASH SET CALCULO_AA= Decode(INDICADOR_AA,0,0,((INDICADOR_AA_KOF)/(INDICADOR_AA))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET CALCULO_MES= Decode(INDICADOR_MES,0,0,((INDICADOR_MES_KOF)/(INDICADOR_MES))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET CALCULO_YTD_AA= Decode(INDICADOR_YTD_AA,0,0,((INDICADOR_YTD_AA_KOF)/(INDICADOR_YTD_AA))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET CALCULO_YTD_MES= Decode(INDICADOR_YTD_MES,0,0,((INDICADOR_YTD_MES_KOF)/(INDICADOR_YTD_MES))*100)
WHERE PAIS = 'NOMBREPAIS';
COMMIT;


/****** CALCULA VARIACIONES PP ******/

UPDATE SHARE_ST_INFO_CANAL_DASH SET VARIACION_PP= CALCULO_MES-CALCULO_AA
WHERE PAIS = 'NOMBREPAIS';
COMMIT;

UPDATE SHARE_ST_INFO_CANAL_DASH SET VARIACION_YTD_PP= CALCULO_YTD_MES-CALCULO_YTD_AA
WHERE PAIS = 'NOMBREPAIS';
COMMIT;
