/********************* SHARE - CARGA DE DIMENSIONES **************************/

/****** CARGA DE CATALOGO INDICADORES **********/

MERGE INTO SHARE_DIM_INDICADOR I
USING (SELECT DISTINCT INDICADOR FROM SHARE_ST_INFO_G_CAT_DASH)TMP 
ON (I.GV_INDICADOR=TMP.INDICADOR)
WHEN NOT MATCHED THEN
INSERT(PK_INDICADOR, GV_INDICADOR)
VALUES(SEQ_PK_INDICADOR_SHARE.NEXTVAL,TMP.INDICADOR);
COMMIT;

EXIT;