/********************* SHARE - INSERTA REGISTROS EN TABLA DE HECHOS DASHBOARD**************************/

/****** TRUNCA TABLA DE HECHOS Y AGREGADAS **********/

TRUNCATE TABLE SHARE_AGG_INFO_G_CAT_DASH;
TRUNCATE TABLE SHARE_AGG_INFO_CAT_DASH;
TRUNCATE TABLE SHARE_AGG_INFO_CANAL_DASH;

TRUNCATE TABLE SHARE_AGG_INFO_G_CAT_FAB_DASH;
TRUNCATE TABLE SHARE_AGG_INFO_CAT_FAB_DASH;
TRUNCATE TABLE SHARE_AGG_INFO_GCANAL_FAB_DASH;
TRUNCATE TABLE SHARE_AGG_INFO_CANAL_FAB_DASH;


/****** BORRA SECUENCIAS **********/

DROP SEQUENCE SEQ_AGG_REG_SHARE_7;
DROP SEQUENCE SEQ_AGG_REG_SHARE_8;
DROP SEQUENCE SEQ_AGG_REG_SHARE_9;
DROP SEQUENCE SEQ_AGG_REG_SHARE_10;
DROP SEQUENCE SEQ_AGG_REG_SHARE_11;
DROP SEQUENCE SEQ_AGG_REG_SHARE_12;
DROP SEQUENCE SEQ_AGG_REG_SHARE_13;

/****** RECREA SECUENCIAS **********/


CREATE SEQUENCE SEQ_AGG_REG_SHARE_7
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_8
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_9
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_10
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_11
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_12
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

CREATE SEQUENCE SEQ_AGG_REG_SHARE_13
START WITH 1
INCREMENT BY 1
NOMAXVALUE ;

/****** INSERTA REGISTROS A TABLA AGREGADA G_CATEGORIA  **********/

INSERT INTO SHARE_AGG_INFO_G_CAT_DASH
SELECT
SEQ_AGG_REG_SHARE_11.NEXTVAL,
PK_INDICADOR,
ID_TIEMPO,
PK_PAIS,
NVL(PK_GRUPO_CATEGORIA,0),
INDICADOR_AA,
INDICADOR_AA_KOF,
INDICADOR_AA_TOTAL,
CALCULO_AA,
INDICADOR_MES,
INDICADOR_MES_KOF,
INDICADOR_MES_TOTAL,
CALCULO_MES,
VARIACION_PP,
INDICADOR_YTD_AA,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_AA_TOTAL,
CALCULO_YTD_AA,
INDICADOR_YTD_MES,
INDICADOR_YTD_MES_KOF,
INDICADOR_YTD_MES_TOTAL,
CALCULO_YTD_MES,
VARIACION_YTD_PP
FROM SHARE_ST_INFO_G_CAT_DASH TMP
LEFT JOIN SHARE_DIM_INDICADOR DI
ON TMP.INDICADOR=DI.GV_INDICADOR
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES=UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA;
COMMIT;

INSERT INTO SHARE_AGG_INFO_G_CAT_FAB_DASH
SELECT
SEQ_AGG_REG_SHARE_12.NEXTVAL,
PK_INDICADOR,
ID_TIEMPO,
PK_PAIS,
NVL(PK_GRUPO_CATEGORIA,0),
PK_FABRICANTE,
INDICADOR_AA,
INDICADOR_AA_KOF,
INDICADOR_AA_TOTAL,
CALCULO_AA,
INDICADOR_MES,
INDICADOR_MES_KOF,
INDICADOR_MES_TOTAL,
CALCULO_MES,
VARIACION_PP,
INDICADOR_YTD_AA,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_AA_TOTAL,
CALCULO_YTD_AA,
INDICADOR_YTD_MES,
INDICADOR_YTD_MES_KOF,
INDICADOR_YTD_MES_TOTAL,
CALCULO_YTD_MES,
VARIACION_YTD_PP
FROM SHARE_ST_INFO_G_CAT_FAB_DASH TMP
LEFT JOIN SHARE_DIM_INDICADOR DI
ON TMP.INDICADOR=DI.GV_INDICADOR
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES=UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE;
COMMIT;

INSERT INTO SHARE_AGG_INFO_CAT_DASH
SELECT
SEQ_AGG_REG_SHARE_13.NEXTVAL,
PK_INDICADOR,
ID_TIEMPO,
PK_PAIS,
PK_GRUPO_CATEGORIA,
NVL(PK_CATEGORIA,0),
INDICADOR_AA,
INDICADOR_AA_KOF,
INDICADOR_AA_TOTAL,
CALCULO_AA,
INDICADOR_MES,
INDICADOR_MES_KOF,
INDICADOR_MES_TOTAL,
CALCULO_MES,
VARIACION_PP,
INDICADOR_YTD_AA,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_AA_TOTAL,
CALCULO_YTD_AA,
INDICADOR_YTD_MES,
INDICADOR_YTD_MES_KOF,
INDICADOR_YTD_MES_TOTAL,
CALCULO_YTD_MES,
VARIACION_YTD_PP
FROM SHARE_ST_INFO_CAT_DASH TMP
LEFT JOIN SHARE_DIM_INDICADOR DI
ON TMP.INDICADOR=DI.GV_INDICADOR
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES=UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIAS DC
ON NVL(TMP.CATEGORIA,'#')= NVL(DC.GV_CATEGORIA,'#');
COMMIT;

INSERT INTO SHARE_AGG_INFO_CAT_FAB_DASH
SELECT
SEQ_AGG_REG_SHARE_7.NEXTVAL,
PK_INDICADOR,
ID_TIEMPO,
PK_PAIS,
PK_GRUPO_CATEGORIA,
NVL(PK_CATEGORIA,0),
PK_FABRICANTE,
INDICADOR_AA,
INDICADOR_AA_KOF,
INDICADOR_AA_TOTAL,
CALCULO_AA,
INDICADOR_MES,
INDICADOR_MES_KOF,
INDICADOR_MES_TOTAL,
CALCULO_MES,
VARIACION_PP,
INDICADOR_YTD_AA,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_AA_TOTAL,
CALCULO_YTD_AA,
INDICADOR_YTD_MES,
INDICADOR_YTD_MES_KOF,
INDICADOR_YTD_MES_TOTAL,
CALCULO_YTD_MES,
VARIACION_YTD_PP
FROM SHARE_ST_INFO_CAT_FAB_DASH TMP
LEFT JOIN SHARE_DIM_INDICADOR DI
ON TMP.INDICADOR=DI.GV_INDICADOR
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES=UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIAS DC
ON TMP.CATEGORIA=DC.GV_CATEGORIA
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE;
COMMIT;

INSERT INTO SHARE_AGG_INFO_CANAL_DASH
SELECT
SEQ_AGG_REG_SHARE_8.NEXTVAL,
PK_INDICADOR,
ID_TIEMPO,
PK_PAIS,
NVL(PK_GRUPO_CATEGORIA,0),
NVL(PK_CATEGORIA,0),
PK_CANAL,
INDICADOR_AA,
INDICADOR_AA_KOF,
INDICADOR_AA_TOTAL,
CALCULO_AA,
INDICADOR_MES,
INDICADOR_MES_KOF,
INDICADOR_MES_TOTAL,
CALCULO_MES,
VARIACION_PP,
INDICADOR_YTD_AA,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_AA_TOTAL,
CALCULO_YTD_AA,
INDICADOR_YTD_MES,
INDICADOR_YTD_MES_KOF,
INDICADOR_YTD_MES_TOTAL,
CALCULO_YTD_MES,
VARIACION_YTD_PP
FROM SHARE_ST_INFO_CANAL_DASH TMP
LEFT JOIN SHARE_DIM_INDICADOR DI
ON TMP.INDICADOR=DI.GV_INDICADOR
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES=UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIAS DC
ON NVL(TMP.CATEGORIA,'#')= NVL(DC.GV_CATEGORIA,'#')
LEFT JOIN SHARE_DIM_CANALES DCAN
ON TMP.CANAL=DCAN.GV_CANAL;
COMMIT;

INSERT INTO SHARE_AGG_INFO_CANAL_FAB_DASH
SELECT
SEQ_AGG_REG_SHARE_9.NEXTVAL,
PK_INDICADOR,
ID_TIEMPO,
PK_PAIS,
NVL(PK_GRUPO_CATEGORIA,0),
NVL(PK_CATEGORIA,0),
PK_CANAL,
PK_FABRICANTE,
INDICADOR_AA,
INDICADOR_AA_KOF,
INDICADOR_AA_TOTAL,
CALCULO_AA,
INDICADOR_MES,
INDICADOR_MES_KOF,
INDICADOR_MES_TOTAL,
CALCULO_MES,
VARIACION_PP,
INDICADOR_YTD_AA,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_AA_TOTAL,
CALCULO_YTD_AA,
INDICADOR_YTD_MES,
INDICADOR_YTD_MES_KOF,
INDICADOR_YTD_MES_TOTAL,
CALCULO_YTD_MES,
VARIACION_YTD_PP
FROM SHARE_ST_INFO_CANAL_FAB_DASH TMP
LEFT JOIN SHARE_DIM_INDICADOR DI
ON TMP.INDICADOR=DI.GV_INDICADOR
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES=UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CATEGORIAS DC
ON TMP.CATEGORIA=DC.GV_CATEGORIA
LEFT JOIN SHARE_DIM_CANALES DCAN
ON TMP.CANAL=DCAN.GV_CANAL
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE;
COMMIT;

INSERT INTO SHARE_AGG_INFO_GCANAL_FAB_DASH
SELECT
SEQ_AGG_REG_SHARE_10.NEXTVAL,
PK_INDICADOR,
ID_TIEMPO,
PK_PAIS,
NVL(PK_GRUPO_CATEGORIA,0),
PK_CANAL,
PK_FABRICANTE,
INDICADOR_AA,
INDICADOR_AA_KOF,
INDICADOR_AA_TOTAL,
CALCULO_AA,
INDICADOR_MES,
INDICADOR_MES_KOF,
INDICADOR_MES_TOTAL,
CALCULO_MES,
VARIACION_PP,
INDICADOR_YTD_AA,
INDICADOR_YTD_AA_KOF,
INDICADOR_YTD_AA_TOTAL,
CALCULO_YTD_AA,
INDICADOR_YTD_MES,
INDICADOR_YTD_MES_KOF,
INDICADOR_YTD_MES_TOTAL,
CALCULO_YTD_MES,
VARIACION_YTD_PP
FROM SHARE_ST_INFO_G_CANAL_FAB_DASH TMP
LEFT JOIN SHARE_DIM_INDICADOR DI
ON TMP.INDICADOR=DI.GV_INDICADOR
LEFT JOIN SHARE_DIM_TIEMPO DT
ON TMP.ANIO=DT.GV_ANIO AND TMP.MES=UPPER(DT.GV_MESCORTO)
LEFT JOIN SHARE_DIM_PAISES DP
ON TMP.PAIS=DP.GV_PAIS
LEFT JOIN SHARE_DIM_GRUPO_CATEGORIAS DG
ON TMP.GRUPO_CATEGORIA=DG.GV_GRUPO_CATEGORIA
LEFT JOIN SHARE_DIM_CANALES DCAN
ON TMP.CANAL=DCAN.GV_CANAL
LEFT JOIN SHARE_DIM_FABRICANTES DF
ON TMP.FABRICANTE=DF.GV_FABRICANTE;
COMMIT;
